# Generated by Django 3.2.19 on 2025-03-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=36)),
                ('user_id', models.CharField(max_length=36)),
                ('item_id', models.CharField(max_length=36)),
                ('total_amount', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Completed')])),
            ],
        ),
    ]
