# Generated by Django 3.2.19 on 2025-03-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Processing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
