# Generated by Django 3.2.19 on 2025-03-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processing', '0003_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('Pending', 1), ('Processing', 2), ('Completed', 3)]),
        ),
    ]
