# Generated by Django 3.2.19 on 2025-03-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processing', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 1), ('Processing', 2), ('Completed', 3)], max_length=10),
        ),
    ]
