# Generated by Django 3.2.19 on 2025-03-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processing', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
