# Generated by Django 3.2.19 on 2025-03-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processing', '0006_auto_20250301_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processing_time',
            field=models.IntegerField(null=True),
        ),
    ]
